import React from "react";
import Tarjetas from "./Tarjetas.jsx";
import "./Home.css";
const Home = () => {
  return (
    <div>
      <h4 className="H4">Colección</h4>
      <div id="contenedorTarjetas" className="container">
        <Tarjetas
          className="c1"
          imagen="https://picsum.photos/500/300"
          haiku="Haikuuuuuuu"
          fotoDePerfil="https://www.ellitoral.com//um/fotos/310346_iorio.jpg"
          nombreDeHaiku="Haiku"
          IconoCompartir="/"
        />
        <Tarjetas
          className="c2"
          imagen="https://picsum.photos/500/300"
          haiku="Haikuuuuuuu"
          fotoDePerfil="https://www.ellitoral.com//um/fotos/310346_iorio.jpg"
          nombreDeHaiku="Haiku"
          IconoCompartir="/"
        />
        <Tarjetas
          className="c3"
          imagen="https://picsum.photos/500/300"
          haiku="Haikuuuuuuu"
          fotoDePerfil="https://www.ellitoral.com//um/fotos/310346_iorio.jpg"
          nombreDeHaiku="Haiku"
          IconoCompartir="/"
        />
        <Tarjetas
          className="c4"
          imagen="https://picsum.photos/500/300"
          haiku="Haikuuuuuuu"
          fotoDePerfil="https://www.ellitoral.com//um/fotos/310346_iorio.jpg"
          nombreDeHaiku="Haiku"
          IconoCompartir="/"
        />
        <Tarjetas
          className="c5"
          imagen="https://picsum.photos/500/300"
          haiku="Haikuuuuuuu"
          fotoDePerfil="https://www.ellitoral.com//um/fotos/310346_iorio.jpg"
          nombreDeHaiku="Haiku"
          IconoCompartir="/"
        />
        <Tarjetas
          className="c6"
          imagen="https://picsum.photos/500/300"
          haiku="Haikuuuuuuu"
          fotoDePerfil="https://www.ellitoral.com//um/fotos/310346_iorio.jpg"
          nombreDeHaiku="Haiku"
          IconoCompartir="/"
        />
        <Tarjetas
          className="c7"
          imagen="https://picsum.photos/500/300"
          haiku="Haikuuuuuuu"
          fotoDePerfil="https://www.ellitoral.com//um/fotos/310346_iorio.jpg"
          nombreDeHaiku="Haiku"
          IconoCompartir="/"
        />
        <Tarjetas
          className="c8"
          imagen="https://picsum.photos/500/300"
          haiku="Haikuuuuuuu"
          fotoDePerfil="https://www.ellitoral.com//um/fotos/310346_iorio.jpg"
          nombreDeHaiku="Haiku"
          IconoCompartir="/"
        />
         <Tarjetas
          className="c8"
          imagen="https://picsum.photos/500/300"
          haiku="Haikuuuuuuu"
          fotoDePerfil="https://www.ellitoral.com//um/fotos/310346_iorio.jpg"
          nombreDeHaiku="Haiku"
          IconoCompartir="/"
        />
         <Tarjetas
          className="c8"
          imagen="https://picsum.photos/500/300"
          haiku="Haikuuuuuuu"
          fotoDePerfil="https://www.ellitoral.com//um/fotos/310346_iorio.jpg"
          nombreDeHaiku="Haiku"
          IconoCompartir="/"
        />
         <Tarjetas
          className="c8"
          imagen="https://picsum.photos/500/300"
          haiku="Haikuuuuuuu"
          fotoDePerfil="https://www.ellitoral.com//um/fotos/310346_iorio.jpg"
          nombreDeHaiku="Haiku"
          IconoCompartir="/"
        />
         <Tarjetas
          className="c8"
          imagen="https://picsum.photos/500/300"
          haiku="Haikuuuuuuu"
          fotoDePerfil="https://www.ellitoral.com//um/fotos/310346_iorio.jpg"
          nombreDeHaiku="Haiku"
          IconoCompartir="/"
        />
      </div>
    </div>
  );
};

export default Home;
